tunnel: aef29b23-3e69-4b99-b74d-29ffa1374cb6
credentials-file: /etc/cloudflared/<TON_UUID_TUNNEL_QIP>.json
loglevel: debug

ingress:
  # Backend staging
  - hostname: staging-api.qip.ovh
    service: http://qip_api_staging:80

  # Backend production
  - hostname: api.qip.ovh
    service: http://qip_api_prod:80

  # Frontend staging
  - hostname: staging.qip.ovh
    service: http://frontend_staging:80

  # Frontend production
  - hostname: qip.ovh
    service: http://frontend_prod:80

  # Catch-all route
  - service: http_status:404
